# Proxy missing local assets to production
location ~* ^/uploads/(.*)$ {
    try_files $uri @prod_assets;
}

location @prod_assets {
    resolver 8.8.8.8;
    proxy_pass https://www.siteurl.com$request_uri;
    proxy_set_header Host www.siteurl.com;
    proxy_ssl_server_name on;
}